"""Tests for the reproducible official-PyPI lock hash augmentation tool."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = ROOT / "requirements" / "enrich_pypi_hashes.py"


def _load_enricher():
    spec = importlib.util.spec_from_file_location("lock_hash_enricher", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_enricher_replaces_only_hash_blocks_with_official_release_hashes(
    monkeypatch, tmp_path
):
    enricher = _load_enricher()
    source = tmp_path / "base.txt"
    output = tmp_path / "portable.txt"
    source.write_text(
        """# generated by pip-compile
requests==2.34.2 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    # via project
coverage[toml]==7.15.4 \\
    --hash=sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    # via pytest-cov
""",
        encoding="utf-8",
    )

    official_hashes = {
        ("requests", "2.34.2"): ["1" * 64, "2" * 64],
        ("coverage", "7.15.4"): ["3" * 64],
    }
    monkeypatch.setattr(
        enricher,
        "fetch_hashes",
        lambda name, version, *_args: official_hashes[(name, version)],
    )

    entries, hashes = enricher.enrich(
        source,
        output,
        timeout=1,
        retries=1,
        max_entries=10,
        max_files=10,
    )

    rendered = output.read_text(encoding="utf-8")
    assert (entries, hashes) == (2, 3)
    assert "a" * 64 not in rendered
    assert "b" * 64 not in rendered
    assert "    # via project" in rendered
    assert "    # via pytest-cov" in rendered
    assert rendered.count("--hash=sha256:") == 3
    assert "coverage[toml]==7.15.4" in rendered


def test_enricher_writes_one_replacement_lock_input_fingerprint(monkeypatch, tmp_path):
    enricher = _load_enricher()
    source = tmp_path / "base.txt"
    output = tmp_path / "portable.txt"
    source.write_text(
        "# eqlib-lock-input-sha256: v1:" + "a" * 64 + "\n"
        "requests==2.34.2 \\\n"
        "    --hash=sha256:" + "b" * 64 + "\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(enricher, "fetch_hashes", lambda *_args: ["1" * 64])

    enricher.enrich(
        source,
        output,
        timeout=1,
        retries=1,
        max_entries=10,
        max_files=10,
        lock_input_fingerprint="# eqlib-lock-input-sha256: v1:" + "c" * 64,
    )

    rendered = output.read_text(encoding="utf-8")
    assert rendered.count("eqlib-lock-input-sha256:") == 1
    assert "# eqlib-lock-input-sha256: v1:" + "c" * 64 in rendered


@pytest.mark.parametrize(
    "invalid_tail",
    [
        "not a valid requirement @@@\n",
        "--index-url https://example.invalid/simple\n",
        "requests @ https://example.invalid/requests.whl \\\n"
        "    --hash=sha256:" + "c" * 64 + "\n",
        "    --hash=sha256:" + "z" * 64 + "\n",
    ],
)
def test_enricher_fails_closed_without_replacing_output_on_unsupported_lock_syntax(
    monkeypatch, tmp_path, invalid_tail
):
    enricher = _load_enricher()
    source = tmp_path / "base.txt"
    output = tmp_path / "portable.txt"
    source.write_text(
        "requests==2.34.2 \\\n" "    --hash=sha256:" + "a" * 64 + "\n" + invalid_tail,
        encoding="utf-8",
    )
    output.write_text("sentinel\n", encoding="utf-8")
    monkeypatch.setattr(enricher, "fetch_hashes", lambda *_args: ["1" * 64])

    with pytest.raises(ValueError):
        enricher.enrich(
            source,
            output,
            timeout=1,
            retries=1,
            max_entries=10,
            max_files=10,
        )

    assert output.read_text(encoding="utf-8") == "sentinel\n"


def test_enricher_rejects_pypi_release_when_any_file_lacks_valid_sha256(monkeypatch):
    enricher = _load_enricher()

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self, _limit):
            return json.dumps(
                {
                    "urls": [
                        {"digests": {"sha256": "1" * 64}},
                        {"digests": {}},
                    ]
                }
            ).encode("utf-8")

    monkeypatch.setattr(enricher, "urlopen", lambda *_args, **_kwargs: Response())

    with pytest.raises(RuntimeError, match="invalid or missing SHA256"):
        enricher.fetch_hashes("requests", "2.34.2", 1, 1, 10)


def test_enricher_rejects_non_mapping_pypi_digests(monkeypatch):
    enricher = _load_enricher()

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self, _limit):
            return json.dumps({"urls": [{"digests": []}]}).encode("utf-8")

    monkeypatch.setattr(enricher, "urlopen", lambda *_args, **_kwargs: Response())

    with pytest.raises(RuntimeError, match="invalid or missing SHA256"):
        enricher.fetch_hashes("requests", "2.34.2", 1, 1, 10)
