"""Tests for the reproducible official-PyPI lock hash augmentation tool."""

from __future__ import annotations

import importlib.util
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = ROOT / "requirements" / "enrich_pypi_hashes.py"


def _load_enricher():
    spec = importlib.util.spec_from_file_location("lock_hash_enricher", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_enricher_replaces_only_hash_blocks_with_official_release_hashes(
    monkeypatch, tmp_path
):
    enricher = _load_enricher()
    source = tmp_path / "base.txt"
    output = tmp_path / "portable.txt"
    source.write_text(
        """# generated by pip-compile
requests==2.34.2 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    # via project
coverage[toml]==7.15.4 \\
    --hash=sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    # via pytest-cov
""",
        encoding="utf-8",
    )

    official_hashes = {
        ("requests", "2.34.2"): ["1" * 64, "2" * 64],
        ("coverage", "7.15.4"): ["3" * 64],
    }
    monkeypatch.setattr(
        enricher,
        "fetch_hashes",
        lambda name, version, *_args: official_hashes[(name, version)],
    )

    entries, hashes = enricher.enrich(
        source,
        output,
        timeout=1,
        retries=1,
        max_entries=10,
        max_files=10,
    )

    rendered = output.read_text(encoding="utf-8")
    assert (entries, hashes) == (2, 3)
    assert "a" * 64 not in rendered
    assert "b" * 64 not in rendered
    assert "    # via project" in rendered
    assert "    # via pytest-cov" in rendered
    assert rendered.count("--hash=sha256:") == 3
    assert "coverage[toml]==7.15.4" in rendered
