"""Example 20: All-Weather Alpha Strategy -- Backtest Runner.

Runs a multi-year backtest on the combined multi-layer strategy using
12 diversified A-share stocks across 8 sectors.

The combined strategy integrates:
  - Multi-factor stock selection (momentum + volume + reversal + volatility)
  - Z-score factor normalisation
  - Sector-rotation scoring
  - RSI + Bollinger Band mean-reversion entry/exit
  - MACD trend confirmation
  - ATR trailing stop
  - Donchian Channel breakout exit
  - Support/Resistance confirmation
  - Lifecycle callbacks (before_trading_start / after_trading_end)

See combined_strategy.py for full strategy documentation.

Usage:
    python examples/20_all_weather_alpha/run_backtest.py
    python examples/20_all_weather_alpha/run_backtest.py --cash 1000000
    python examples/20_all_weather_alpha/run_backtest.py --start 2021-01-01 --end 2024-12-31

Output:
    Reports and charts generated by run_strategy().
"""

import argparse
import os
import sys

# ---------------------------------------------------------------------------
# Make the local package importable (same pattern as other examples)
# ---------------------------------------------------------------------------
_here = os.path.dirname(os.path.abspath(__file__))
if _here not in sys.path:
    sys.path.insert(0, _here)

from combined_strategy import initialize, STOCK_POOL  # noqa: E402
from eqlib import run_strategy  # noqa: E402
from examples._defaults import (  # noqa: E402
    INDEX_HS300, INITIAL_CASH, START_DATE, END_DATE,
    verify_data_available, print_evaluation,
)


def main():
    parser = argparse.ArgumentParser(
        description="Backtest the All-Weather Alpha combined strategy"
    )
    parser.add_argument(
        "--cash", type=float, default=500_000,
        help="Starting capital in CNY (default: 500000)"
    )
    parser.add_argument(
        "--start", type=str, default=START_DATE,
        help="Backtest start date YYYY-MM-DD (default: %s)" % START_DATE
    )
    parser.add_argument(
        "--end", type=str, default=END_DATE,
        help="Backtest end date YYYY-MM-DD (default: %s)" % END_DATE
    )
    args = parser.parse_args()

    print("=" * 65)
    print("  All-Weather Alpha -- Combined Strategy Backtest")
    print("=" * 65)
    print("  Period      : %s  ->  %s" % (args.start, args.end))
    print("  Capital     : %.0f CNY" % args.cash)
    print("  Benchmark   : CSI 300 (%s)" % INDEX_HS300)
    print("  Stock pool  : %d stocks across 8 sectors" % len(STOCK_POOL))
    for code in STOCK_POOL:
        print("                %s" % code)
    print()

    # ------------------------------------------------------------------
    # Verify data availability before running the full backtest
    # ------------------------------------------------------------------
    print("Verifying data availability...")
    sample = STOCK_POOL[0]
    actual_start, actual_end = verify_data_available(
        sample, args.start, args.end)
    if actual_start != args.start:
        print("  Adjusted start date to %s for data availability." % actual_start)
        args.start = actual_start
    print("  Data OK for %s (%s -> %s)" % (sample, actual_start, actual_end))
    print()

    # ------------------------------------------------------------------
    # Run backtest
    # ------------------------------------------------------------------
    result = run_strategy(
        initialize_func=initialize,
        start_date=args.start,
        end_date=args.end,
        starting_cash=args.cash,
        benchmark=INDEX_HS300,
        securities=STOCK_POOL,
    )

    if result is None:
        print("Backtest failed: no result returned.")
        sys.exit(1)

    # ------------------------------------------------------------------
    # Summary output
    # ------------------------------------------------------------------
    context = result["context"]
    final_val = context.portfolio.total_value
    pnl = final_val - args.cash
    pnl_pct = pnl / args.cash * 100
    trade_count = len(result["trade_log"])

    print()
    print("=" * 65)
    print("  Backtest Results")
    print("=" * 65)
    print("  Starting cash : %.2f CNY" % args.cash)
    print("  Final value   : %.2f CNY" % final_val)
    print("  Total P&L     : %+.2f CNY  (%+.2f%%)" % (pnl, pnl_pct))
    print("  Total trades  : %d" % trade_count)

    # ------------------------------------------------------------------
    # Risk/return metrics via shared evaluator
    # ------------------------------------------------------------------
    print_evaluation(result, strategy_name="All-Weather Alpha")


if __name__ == "__main__":
    main()
