#!/usr/bin/env python3
"""Select the supported Python 3.10 macOS-arm64/Linux-x86_64 slice of a uv lock.

``uv pip compile --universal --generate-hashes --no-strip-markers`` emits a
single, marker-aware resolution for more Python versions and platforms than
this project supports.  This bounded post-processing step keeps only entries
active for four checked Python 3.10 boundary/runtime marker environments,
preserving
their explicit markers and generated hashes.  It is intentionally not a
resolver and fails before replacing its output when the input is malformed.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable
import os
from pathlib import Path
import re
import tempfile
from typing import NamedTuple

from packaging.markers import default_environment
from packaging.requirements import InvalidRequirement, Requirement
from packaging.utils import canonicalize_name


_HASH = re.compile(r"--hash=sha256:([0-9a-fA-F]{64})")
_HEADER = """# This file is autogenerated by the documented Python 3.10 four-target lock pipeline.
# It retains entries active at CPython 3.10.0 or 3.10.20 on macOS arm64 and manylinux x86_64.
# Run requirements/enrich_pypi_hashes.py afterwards to replace these resolver hashes
# with the complete official PyPI release hash set and add the lock-input fingerprint.

"""


def _marker_environment(
    *,
    platform_machine: str,
    platform_system: str,
    sys_platform: str,
    python_full_version: str,
) -> dict[str, str]:
    environment = default_environment()
    environment.update(
        {
            "implementation_name": "cpython",
            "implementation_version": python_full_version,
            "os_name": "posix",
            "platform_machine": platform_machine,
            "platform_python_implementation": "CPython",
            "platform_release": "",
            "platform_system": platform_system,
            "platform_version": "",
            "python_full_version": python_full_version,
            "python_version": "3.10",
            "sys_platform": sys_platform,
            "extra": "",
        }
    )
    return {key: str(value) for key, value in environment.items()}


_TARGET_ENVIRONMENTS = (
    (
        "cpython-3.10.0-macos-arm64",
        _marker_environment(
            platform_machine="arm64",
            platform_system="Darwin",
            sys_platform="darwin",
            python_full_version="3.10.0",
        ),
    ),
    (
        "cpython-3.10.20-macos-arm64",
        _marker_environment(
            platform_machine="arm64",
            platform_system="Darwin",
            sys_platform="darwin",
            python_full_version="3.10.20",
        ),
    ),
    (
        "cpython-3.10.0-manylinux-x86_64",
        _marker_environment(
            platform_machine="x86_64",
            platform_system="Linux",
            sys_platform="linux",
            python_full_version="3.10.0",
        ),
    ),
    (
        "cpython-3.10.20-manylinux-x86_64",
        _marker_environment(
            platform_machine="x86_64",
            platform_system="Linux",
            sys_platform="linux",
            python_full_version="3.10.20",
        ),
    ),
)


class Entry(NamedTuple):
    """A validated exact requirement and all hashes that belong to it."""

    requirement: Requirement
    hashes: tuple[str, ...]


def select(input_path: Path, output_path: Path, *, max_entries: int = 200) -> int:
    """Atomically select the four-target Python 3.10 subset of a uv lock."""
    if max_entries < 1:
        raise ValueError("max_entries must be positive")
    lines = input_path.read_text(encoding="utf-8").splitlines(keepends=True)
    entries = _read_entries(lines)
    if not entries:
        raise ValueError("universal lock contains no exact pinned requirements")
    if len(entries) > max_entries:
        raise ValueError(
            f"universal lock has {len(entries)} entries, above limit {max_entries}"
        )

    selected = [entry for entry in entries if _is_active_for_targets(entry.requirement)]
    if not selected:
        raise ValueError("universal lock has no entries active for Python 3.10 targets")
    _validate_unique_entries(selected)
    rendered = _render(selected)
    _atomic_write(output_path, rendered)
    return len(selected)


def _read_entries(lines: list[str]) -> list[Entry]:
    entries = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip() or line.lstrip().startswith("#"):
            index += 1
            continue
        entry, index = _parse_entry(lines, index)
        entries.append(entry)
    return entries


def _parse_entry(lines: list[str], start: int) -> tuple[Entry, int]:
    source = lines[start]
    stripped = source.strip()
    if source[:1].isspace() or stripped.startswith("-"):
        raise ValueError(f"line {start + 1}: unsupported top-level lock syntax")
    if not source.rstrip().endswith("\\"):
        raise ValueError(f"line {start + 1}: exact pin must begin a hash continuation")
    requirement_text = source.rstrip()[:-1].rstrip()
    try:
        requirement = Requirement(requirement_text)
    except InvalidRequirement as exc:
        raise ValueError(
            f"line {start + 1}: invalid requirement {requirement_text!r}"
        ) from exc
    if requirement.url:
        raise ValueError(f"line {start + 1}: direct URL requirements are unsupported")
    specifiers = list(requirement.specifier)
    exact = [specifier for specifier in specifiers if specifier.operator == "=="]
    if len(specifiers) != 1 or len(exact) != 1:
        raise ValueError(f"line {start + 1}: expected one exact == pin")

    hashes: list[tuple[str, bool]] = []
    index = start + 1
    while index < len(lines):
        candidate = lines[index]
        candidate_stripped = candidate.strip()
        if not candidate_stripped or candidate_stripped.startswith("#"):
            index += 1
            continue
        if not candidate[:1].isspace():
            break
        value = candidate_stripped
        continued = value.endswith("\\")
        if continued:
            value = value[:-1].rstrip()
        match = _HASH.fullmatch(value)
        if match is None:
            raise ValueError(f"line {index + 1}: malformed SHA-256 hash continuation")
        hashes.append((match.group(1).lower(), continued))
        index += 1

    if not hashes:
        raise ValueError(f"line {start + 1}: exact pin has no SHA-256 hash")
    if any(not continued for _hash, continued in hashes[:-1]):
        raise ValueError(f"line {start + 1}: hash continuation ended before final hash")
    return Entry(requirement, tuple(hash for hash, _continued in hashes)), index


def _is_active_for_targets(requirement: Requirement) -> bool:
    return requirement.marker is None or any(
        requirement.marker.evaluate(environment)
        for _target_name, environment in _TARGET_ENVIRONMENTS
    )


def _validate_unique_entries(entries: Iterable[Entry]) -> None:
    seen: dict[tuple[str, str], Entry] = {}
    for entry in entries:
        name = canonicalize_name(entry.requirement.name)
        for target_name, environment in _TARGET_ENVIRONMENTS:
            if entry.requirement.marker and not entry.requirement.marker.evaluate(
                environment
            ):
                continue
            key = (target_name, name)
            if key in seen:
                raise ValueError(
                    f"overlapping selected requirement for {name} on {target_name}"
                )
            seen[key] = entry


def _render(entries: Iterable[Entry]) -> str:
    ordered = sorted(
        entries,
        key=lambda entry: (
            canonicalize_name(entry.requirement.name),
            str(entry.requirement.specifier),
            str(entry.requirement.marker or ""),
        ),
    )
    lines = [_HEADER]
    for entry in ordered:
        requirement_text = _render_requirement(entry.requirement)
        hashes = sorted(set(entry.hashes))
        lines.append(f"{requirement_text} \\\n")
        for position, digest in enumerate(hashes):
            continuation = " \\" if position + 1 < len(hashes) else ""
            lines.append(f"    --hash=sha256:{digest}{continuation}\n")
    return "".join(lines)


def _render_requirement(requirement: Requirement) -> str:
    rendered = str(requirement)
    if ";" not in rendered:
        return rendered
    base, marker = rendered.split(";", 1)
    return f"{base.rstrip()} ; {marker.strip()}"


def _atomic_write(output_path: Path, value: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output_path.name}.", suffix=".tmp", dir=output_path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as stream:
            stream.write(value)
        os.replace(temporary, output_path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--max-entries", type=int, default=200)
    args = parser.parse_args()
    count = select(args.input, args.output, max_entries=args.max_entries)
    print(f"selected {count} Python 3.10 four-target pins: {args.output}")


if __name__ == "__main__":
    main()
